url: "https://yveshema.github.io"
plugins:
  - jekyll-seo-tag  
  - jekyll-octicons
  - jekyll-gist  
  - jekyll-feed 
  - jekyll-sitemap   

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: pretty     
