plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll-gist
  - jekyll-archives

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: pretty

jekyll-archives:
  enabled: []
  layout: archives
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'


      
